### ISSUE TITLE
TypeError: delete() got an unexpected keyword argument 'save'

### ISSUE THREAD

**Issue by patatetom** [open-iscsi/targetcli-fb#122]
hello,

I'm trying to delete a /backstores/block named test and previously created :

```
/> ls
o- / ..................................................................... [...]
  o- backstores .......................................................... [...]
  | o- block .............................................. [Storage Objects: 1]
  | | o- test ................... [/dev/sdc (15.0GiB) ro write-thru deactivated]
  | |   o- alua ............................................... [ALUA Groups: 1]
  | |     o- default_tg_pt_gp ................... [ALUA state: Active/optimized]
  | o- fileio ............................................. [Storage Objects: 0]
  | o- pscsi .............................................. [Storage Objects: 0]
  | o- ramdisk ............................................ [Storage Objects: 0]
  o- iscsi ........................................................ [Targets: 0]
  o- loopback ..................................................... [Targets: 0]
  o- vhost ........................................................ [Targets: 0]
  o- xen-pvscsi ................................................... [Targets: 0]

/> cd /backstores/block/

/backstores/block> delete test
```

```python
Traceback (most recent call last):
  File "./targetcli", line 4, in <module>
    __import__('pkg_resources').run_script('targetcli-fb===2.1.fb49', 'targetcli')
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(script_code, namespace, namespace)
  File "/root/.local/lib/python3.7/site-packages/targetcli_fb-2.1.fb49-py3.7.egg/EGG-INFO/scripts/targetcli", line 122, in <module>
  File "/root/.local/lib/python3.7/site-packages/targetcli_fb-2.1.fb49-py3.7.egg/EGG-INFO/scripts/targetcli", line 112, in main
  File "/root/.local/lib/python3.7/site-packages/configshell_fb/shell.py", line 905, in run_interactive
    self._cli_loop()
  File "/root/.local/lib/python3.7/site-packages/configshell_fb/shell.py", line 734, in _cli_loop
    self.run_cmdline(cmdline)
  File "/root/.local/lib/python3.7/site-packages/configshell_fb/shell.py", line 848, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/root/.local/lib/python3.7/site-packages/configshell_fb/shell.py", line 823, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/root/.local/lib/python3.7/site-packages/configshell_fb/node.py", line 1406, in execute_command
    return method(*pparams, **kparams)
  File "/root/.local/lib/python3.7/site-packages/targetcli_fb-2.1.fb49-py3.7.egg/targetcli/ui_backstore.py", line 309, in ui_command_delete
TypeError: delete() got an unexpected keyword argument 'save'
```

regards.

**Comment by maurizio-lombardi** [comment]
Hi,

please update the rtslib package to version v2.1.fb69

**Comment by patatetom** [comment]
hi,

I didn't found this version.
the lastest seems to be 2.1.66 :

```
# ll -gG /tmp/iscsi/*.zip
-rw-r--r-- 1 40181 18 sept. 14:03 /tmp/iscsi/configshell-fb-master.zip
-rw-r--r-- 1 56612 18 sept. 14:02 /tmp/iscsi/rtslib-fb-master.zip
-rw-r--r-- 1 41303 18 sept. 14:01 /tmp/iscsi/targetcli-fb-master.zip

# cd /tmp/iscsi/configshell-fb-master/
# python setup.py install --user
...
Finished processing dependencies for configshell-fb==1.1.25

# cd ../rtslib-fb-master/
# python setup.py install --user
...
Finished processing dependencies for rtslib-fb==2.1.63

# cd ../targetcli-fb-master/
# python setup.py install --user
/usr/lib/python3.7/site-packages/setuptools/dist.py:407: UserWarning: The version specified ('2.1.fb49') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
...
Finished processing dependencies for targetcli-fb===2.1.fb49
```

```
# pip list --user
Package        Version 
-------------- --------
configshell-fb 1.1.25  
pyudev         0.21.0  
rtslib-fb      2.1.63  
targetcli-fb   2.1.fb49

# pip search configshell
configshell-fb (1.1.24)  - A framework to implement simple but nice CLIs.
  INSTALLED: 1.1.25
  LATEST:    1.1.24

# pip search rtslib
rtslib-fb (2.1.66)  - API for Linux kernel SCSI target (aka LIO)
  INSTALLED: 2.1.63
  LATEST:    2.1.66
rtstool (0.1a4)     - rtslib command-line interface

# pip search targetcli
```

```
# pip install --upgrade --user rtslib-fb
Collecting rtslib-fb
  Using cached https://files.pythonhosted.org/packages/15/33/879f9e2e97c1cfca0f0d67985769b6ee566ca37abf7c4333d99e9794a1cb/rtslib-fb-2.1.66.tar.gz
Requirement already satisfied, skipping upgrade: pyudev>=0.16.1 in /root/.local/lib/python3.7/site-packages/pyudev-0.21.0-py3.7.egg (from rtslib-fb) (0.21.0)
Requirement already satisfied, skipping upgrade: six in /usr/lib/python3.7/site-packages (from rtslib-fb) (1.11.0)
Installing collected packages: rtslib-fb
  Found existing installation: rtslib-fb 2.1.63
    Uninstalling rtslib-fb-2.1.63:
      Successfully uninstalled rtslib-fb-2.1.63
  Running setup.py install for rtslib-fb ... done
Successfully installed rtslib-fb-2.1.66
Traceback (most recent call last):
  File "/bin/pip", line 11, in <module>
    load_entry_point('pip==18.0', 'console_scripts', 'pip')()
  File "/usr/lib/python3.7/site-packages/pip/_internal/__init__.py", line 310, in main
    return command.main(cmd_args)
  File "/usr/lib/python3.7/site-packages/pip/_internal/basecommand.py", line 180, in main
    timeout=min(5, options.timeout)
  File "/usr/lib/python3.7/site-packages/pip/_internal/basecommand.py", line 77, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/usr/lib/python3.7/site-packages/pip/_internal/download.py", line 337, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/lib/python3.7/site-packages/pip/_internal/download.py", line 126, in user_agent
    setuptools_version = get_installed_version("setuptools")
  File "/usr/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 832, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 562, in __init__
    self.add_entry(entry)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 618, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1883, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1402, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1757, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1634, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1591, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/root/.local/lib/python3.7/site-packages/rtslib_fb-2.1.63-py3.7.egg'

# pip list --user
Package        Version 
-------------- --------
configshell-fb 1.1.25  
pyudev         0.21.0  
rtslib-fb      2.1.66  
targetcli-fb   2.1.fb49
```

```
# pip uninstall rtslib-fb
Uninstalling rtslib-fb-2.1.66:
  Would remove:
    /root/.local/bin/targetctl
    /root/.local/lib/python3.7/site-packages/rtslib/*
    /root/.local/lib/python3.7/site-packages/rtslib_fb-2.1.66-py3.7.egg-info
    /root/.local/lib/python3.7/site-packages/rtslib_fb/*
Proceed (y/n)? y
  Successfully uninstalled rtslib-fb-2.1.66

# pip install --user rtslib-fb
Collecting rtslib-fb
  Using cached https://files.pythonhosted.org/packages/15/33/879f9e2e97c1cfca0f0d67985769b6ee566ca37abf7c4333d99e9794a1cb/rtslib-fb-2.1.66.tar.gz
Requirement already satisfied: pyudev>=0.16.1 in /root/.local/lib/python3.7/site-packages/pyudev-0.21.0-py3.7.egg (from rtslib-fb) (0.21.0)
Requirement already satisfied: six in /usr/lib/python3.7/site-packages (from rtslib-fb) (1.11.0)
Installing collected packages: rtslib-fb
  Running setup.py install for rtslib-fb ... done
Successfully installed rtslib-fb-2.1.66

# pip list --user
Package        Version 
-------------- --------
configshell-fb 1.1.25  
pyudev         0.21.0  
rtslib-fb      2.1.66  
targetcli-fb   2.1.fb49
```

```
# ~/.local/bin/targetctl --help
syntax: /root/.local/bin/targetctl save [file_to_save_to]
        /root/.local/bin/targetctl restore [file_to_restore_from]
        /root/.local/bin/targetctl clear
  default file is: /etc/target/saveconfig.json

# ~/.local/bin/targetcli --help
Usage: /root/.local/bin/targetcli [--version|--help|CMD]
  --version		Print version
  --help		Print this information
  CMD			Run targetcli shell command and exit
  <nothing>		Enter configuration shell
See man page for more information.

# ~/.local/bin/targetcli --version
/root/.local/bin/targetcli version 2.1.fb49
```

```
# ~/.local/bin/targetcli 
targetcli shell version 2.1.fb49
Copyright 2011-2013 by Datera, Inc and others.
For help on commands, type 'help'.

/> ls
o- / ......................................................................................................................... [...]
  o- backstores .............................................................................................................. [...]
  | o- block .................................................................................................. [Storage Objects: 1]
  | | o- test .......................................................................... [/dev/nbd0 (465.8GiB) write-thru activated]
  | |   o- alua ................................................................................................... [ALUA Groups: 1]
  | |     o- default_tg_pt_gp ....................................................................... [ALUA state: Active/optimized]
  | o- fileio ................................................................................................. [Storage Objects: 0]
  | o- pscsi .................................................................................................. [Storage Objects: 0]
  | o- ramdisk ................................................................................................ [Storage Objects: 0]
  o- iscsi ............................................................................................................ [Targets: 1]
  | o- eui.fedcba9876543210 .............................................................................................. [TPGs: 1]
  |   o- tpg1 ............................................................................................... [no-gen-acls, no-auth]
  |     o- acls .......................................................................................................... [ACLs: 1]
  |     | o- eui.0123456789abcdef ................................................................................. [Mapped LUNs: 1]
  |     |   o- mapped_lun0 .................................................................................. [lun0 block/test (rw)]
  |     o- luns .......................................................................................................... [LUNs: 1]
  |     | o- lun0 ...................................................................... [block/test (/dev/nbd0) (default_tg_pt_gp)]
  |     o- portals .................................................................................................... [Portals: 1]
  |       o- 127.0.0.1:3260 ................................................................................................... [OK]
  o- loopback ......................................................................................................... [Targets: 0]
  o- vhost ............................................................................................................ [Targets: 0]
  o- xen-pvscsi ....................................................................................................... [Targets: 0]

/> /iscsi/eui.fedcba9876543210/tpg1/portals/ delete 127.0.0.1 3260
Deleted network portal 127.0.0.1:3260

/> /iscsi/eui.fedcba9876543210/tpg1/luns/ delete 0
Deleted LUN 0.

/> /iscsi/eui.fedcba9876543210/tpg1/acls/ delete eui.0123456789abcdef 
Deleted Node ACL eui.0123456789abcdef.

/> /iscsi/ delete eui.fedcba9876543210 
Deleted Target eui.fedcba9876543210.

/> /backstores/block/ delete test
Traceback (most recent call last):
  File "/root/.local/bin/targetcli", line 4, in <module>
    __import__('pkg_resources').run_script('targetcli-fb===2.1.fb49', 'targetcli')
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(script_code, namespace, namespace)
  File "/root/.local/lib/python3.7/site-packages/targetcli_fb-2.1.fb49-py3.7.egg/EGG-INFO/scripts/targetcli", line 122, in <module>
  File "/root/.local/lib/python3.7/site-packages/targetcli_fb-2.1.fb49-py3.7.egg/EGG-INFO/scripts/targetcli", line 112, in main
  File "/root/.local/lib/python3.7/site-packages/configshell_fb-1.1.25-py3.7.egg/configshell_fb/shell.py", line 905, in run_interactive
    self._cli_loop()
  File "/root/.local/lib/python3.7/site-packages/configshell_fb-1.1.25-py3.7.egg/configshell_fb/shell.py", line 734, in _cli_loop
    self.run_cmdline(cmdline)
  File "/root/.local/lib/python3.7/site-packages/configshell_fb-1.1.25-py3.7.egg/configshell_fb/shell.py", line 848, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/root/.local/lib/python3.7/site-packages/configshell_fb-1.1.25-py3.7.egg/configshell_fb/shell.py", line 823, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/root/.local/lib/python3.7/site-packages/configshell_fb-1.1.25-py3.7.egg/configshell_fb/node.py", line 1406, in execute_command
    return method(*pparams, **kparams)
  File "/root/.local/lib/python3.7/site-packages/targetcli_fb-2.1.fb49-py3.7.egg/targetcli/ui_backstore.py", line 309, in ui_command_delete
TypeError: delete() got an unexpected keyword argument 'save'
```

```
# ~/.local/bin/targetcli 
targetcli shell version 2.1.fb49
Copyright 2011-2013 by Datera, Inc and others.
For help on commands, type 'help'.

/> ls
o- / ......................................................................................................................... [...]
  o- backstores .............................................................................................................. [...]
  | o- block .................................................................................................. [Storage Objects: 1]
  | | o- test ........................................................................ [/dev/nbd0 (465.8GiB) write-thru deactivated]
  | |   o- alua ................................................................................................... [ALUA Groups: 1]
  | |     o- default_tg_pt_gp ....................................................................... [ALUA state: Active/optimized]
  | o- fileio ................................................................................................. [Storage Objects: 0]
  | o- pscsi .................................................................................................. [Storage Objects: 0]
  | o- ramdisk ................................................................................................ [Storage Objects: 0]
  o- iscsi ............................................................................................................ [Targets: 0]
  o- loopback ......................................................................................................... [Targets: 0]
  o- vhost ............................................................................................................ [Targets: 0]
  o- xen-pvscsi ....................................................................................................... [Targets: 0]

/> /backstores/block/test/alua/ delete default_tg_pt_gp 
Can not delete default_tg_pt_gp

/> /backstores/block/ delete test 
Traceback (most recent call last):
  File "/root/.local/bin/targetcli", line 4, in <module>
    __import__('pkg_resources').run_script('targetcli-fb===2.1.fb49', 'targetcli')
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(script_code, namespace, namespace)
  File "/root/.local/lib/python3.7/site-packages/targetcli_fb-2.1.fb49-py3.7.egg/EGG-INFO/scripts/targetcli", line 122, in <module>
  File "/root/.local/lib/python3.7/site-packages/targetcli_fb-2.1.fb49-py3.7.egg/EGG-INFO/scripts/targetcli", line 112, in main
  File "/root/.local/lib/python3.7/site-packages/configshell_fb-1.1.25-py3.7.egg/configshell_fb/shell.py", line 905, in run_interactive
    self._cli_loop()
  File "/root/.local/lib/python3.7/site-packages/configshell_fb-1.1.25-py3.7.egg/configshell_fb/shell.py", line 734, in _cli_loop
    self.run_cmdline(cmdline)
  File "/root/.local/lib/python3.7/site-packages/configshell_fb-1.1.25-py3.7.egg/configshell_fb/shell.py", line 848, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/root/.local/lib/python3.7/site-packages/configshell_fb-1.1.25-py3.7.egg/configshell_fb/shell.py", line 823, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/root/.local/lib/python3.7/site-packages/configshell_fb-1.1.25-py3.7.egg/configshell_fb/node.py", line 1406, in execute_command
    return method(*pparams, **kparams)
  File "/root/.local/lib/python3.7/site-packages/targetcli_fb-2.1.fb49-py3.7.egg/targetcli/ui_backstore.py", line 309, in ui_command_delete
TypeError: delete() got an unexpected keyword argument 'save'
```

**Comment by patatetom** [comment]
hi,

I just found the v2.1.fb69 version and it does fix the problem :

```
# pip install --user https://github.com/open-iscsi/rtslib-fb/archive/v2.1.fb69.tar.gz
Collecting https://github.com/open-iscsi/rtslib-fb/archive/v2.1.fb69.tar.gz
  Downloading https://github.com/open-iscsi/rtslib-fb/archive/v2.1.fb69.tar.gz
     \ 61kB 200kB/s
Requirement already satisfied: pyudev>=0.16.1 in ./.local/lib/python3.7/site-packages/pyudev-0.21.0-py3.7.egg (from rtslib-fb==2.1.69) (0.21.0)
Requirement already satisfied: six in /usr/lib/python3.7/site-packages (from rtslib-fb==2.1.69) (1.11.0)
Installing collected packages: rtslib-fb
  Found existing installation: rtslib-fb 2.1.66
    Uninstalling rtslib-fb-2.1.66:
      Successfully uninstalled rtslib-fb-2.1.66
  Running setup.py install for rtslib-fb ... done
Successfully installed rtslib-fb-2.1.69

# pip list --user
Package        Version 
-------------- --------
configshell-fb 1.1.25  
pyudev         0.21.0  
rtslib-fb      2.1.69  
targetcli-fb   2.1.fb49
```

we get our brushes a little tangled between the different places (PiPA, GitHub, etc...).

thanks Maurizio.
