### ISSUE TITLE
Syntax error in exceptions

### ISSUE THREAD

**Issue by cvubrugier** [open-iscsi/targetcli-fb#142]
With Python 3.7.4 on Debian testing, I see the following syntax error when starting `targetcli`:

    Traceback (most recent call last):
      File "./targetcli", line 4, in <module>
        __import__('pkg_resources').run_script('targetcli-fb===2.1.fb49', 'targetcli')
      File "/home/tof/venv-targetcli/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
        self.require(requires)[0].run_script(script_name, ns)
      File "/home/tof/venv-targetcli/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1452, in run_script
        script_code = compile(script_text, script_filename, 'exec')
      File "/home/tof/venv-targetcli/lib/python3.7/site-packages/targetcli_fb-2.1.fb49-py3.7.egg/EGG-INFO/scripts/targetcli", line 97
        except Exception, e:
                        ^
    SyntaxError: invalid syntax

The correct syntax is `except Exception as e:`. I will provide a fix for this issue.

**Comment by gonzoleeman** [comment]
this issue can be closed now. Please re-open if I'm wrong.
