### ISSUE TITLE
targetcli /iscsi set discovery_auth enable=false" throws an exception

### ISSUE THREAD

**Issue by gonzoleeman** [open-iscsi/targetcli-fb#145]
"targetcli /iscsi set discovery_auth enable=0" works fine, and returns:

> Parameter enable is now 'False'.

So 'false' or 'False' should be accepted.

**Comment by gonzoleeman** [comment]
If you look at other boolean attributes, such as root global tree_show_root, it takes values of "false" or "true", and displaying it likewise returns true or false, unlike "discovery_auth/enable", which takes a 0 or 1 but displays "True" or "False".

I believe this is because the discovery_auth group is set up to assume that all attributes are strings. It would be easy enough to switch "enable" to be boolean, but that would break existing applications. I will instead submit a pull request that just enables "true"/"false" for this string-valued "enable" attribute.

**Comment by ddiss** [comment]
fwiw, I'd be fine if this was fixed by just performing 0/1 validation and returning an error, rather than propagating the exception up to the user:

/iscsi> set discovery_auth enable=false
Traceback (most recent call last):
  File "/usr/bin/targetcli", line 122, in <module>
    main()
  File "/usr/bin/targetcli", line 112, in main
    shell.run_interactive()
  File "/usr/lib/python3.6/site-packages/configshell_fb/shell.py", line 905, in run_interactive
    self._cli_loop()
  File "/usr/lib/python3.6/site-packages/configshell_fb/shell.py", line 734, in _cli_loop
    self.run_cmdline(cmdline)
  File "/usr/lib/python3.6/site-packages/configshell_fb/shell.py", line 848, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/usr/lib/python3.6/site-packages/configshell_fb/shell.py", line 823, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/usr/lib/python3.6/site-packages/configshell_fb/node.py", line 1406, in execute_command
    return method(*pparams, **kparams)
  File "/usr/lib/python3.6/site-packages/configshell_fb/node.py", line 522, in ui_command_set
    group_setter(param, value)
  File "/usr/lib/python3.6/site-packages/targetcli/ui_target.py", line 134, in ui_setgroup_discovery_auth
    self.rtsnode.discovery_enable_auth = value
  File "/usr/lib/python3.6/site-packages/rtslib_fb/fabric.py", line 243, in _set_discovery_enable_auth
    if int(enable):
ValueError: invalid literal for int() with base 10: 'false'

**Comment by gonzoleeman** [comment]
Pull request submitted, which would make the output:

```
# targetcli /iscsi set discovery_auth enable=false
Not setting enable! Syntax error, 'false' is not a NUMBER.
```

**Comment by gonzoleeman** [comment]
Note: my pull request does **not**  make "enable" (in this case) truly boolean, since that would break compatibility. Nor does it attempt to make this attribute some new hybrid between bool and integer. Instead, it just tells the framework it's a numerical attribute, which makes the error handling automatic.

@maurizio-lombardi what do you think? I believe I have the admin ability to merge this myself, but since it's not my code I'd rather have some form of general agreement this is a "good idea" (tm)

**Comment by gonzoleeman** [comment]
I believe this issue has been addressed now.
