### ISSUE TITLE
NotADirectoryError

### ISSUE THREAD

**Issue by DocMAX** [open-iscsi/targetcli-fb#192]
Why i get this error? I am on Arch Linux.
```
docmax@zeus: ~ $ sudo targetcli --version
/usr/bin/targetcli version 2.1.54
```
```
/backstores/block> delete battlenet
Traceback (most recent call last):
  File "/usr/bin/targetcli", line 329, in <module>
    main()
  File "/usr/bin/targetcli", line 317, in main
    shell.run_interactive()
  File "/usr/lib/python3.10/site-packages/configshell_fb/shell.py", line 900, in run_interactive
    self._cli_loop()
  File "/usr/lib/python3.10/site-packages/configshell_fb/shell.py", line 729, in _cli_loop
    self.run_cmdline(cmdline)
  File "/usr/lib/python3.10/site-packages/configshell_fb/shell.py", line 843, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/usr/lib/python3.10/site-packages/configshell_fb/shell.py", line 818, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/usr/lib/python3.10/site-packages/configshell_fb/node.py", line 1406, in execute_command
    return method(*pparams, **kparams)
  File "/usr/lib/python3.10/site-packages/targetcli/ui_backstore.py", line 309, in ui_command_delete
    child.rtsnode.delete(save=save)
  File "/usr/lib/python3.10/site-packages/rtslib_fb/tcm.py", line 269, in delete
    for lun in self._gen_attached_luns():
  File "/usr/lib/python3.10/site-packages/rtslib_fb/tcm.py", line 215, in _gen_attached_luns
    for tpgt_dir in listdir(tpgts_base):
NotADirectoryError: [Errno 20] Not a directory: '/sys/kernel/config/target/iscsi/cpus_allowed_list
```

**Comment by DocMAX** [comment]
OK, self-fixed. There is a new version out for python-rtslib-fb package. PKGBUILD edited for version 2.1.75.

**Comment by maurizio-lombardi** [comment]
Yes, a recent kernel version introduced changes that "broke" rtslib, so distros need to upgrade to 2.1.75
