### ISSUE TITLE
Creating a second LUN gives: "type object 'MappedLUN' has no attribute 'MAX_LUN'"

### ISSUE THREAD

**Issue by tnorman42** [open-iscsi/targetcli-fb#200]
Built from master on Ubuntu 22.04. After this error, if I simply restart targetcli and then save, everything is fine, and the second LUN works.

/iscsi/iqn...../tpg1/luns> create /backstores/block/asante_macbook_tim_tm 
Created LUN 1.
Traceback (most recent call last):
  File "/usr/local/bin/targetcli", line 4, in <module>
    __import__('pkg_resources').run_script('targetcli-fb==2.1.56', 'targetcli')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1460, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.10/dist-packages/targetcli_fb-2.1.56-py3.10.egg/EGG-INFO/scripts/targetcli", line 330, in <module>
  File "/usr/local/lib/python3.10/dist-packages/targetcli_fb-2.1.56-py3.10.egg/EGG-INFO/scripts/targetcli", line 317, in main
  File "/usr/local/lib/python3.10/dist-packages/configshell_fb-1.1.30-py3.10.egg/configshell_fb/shell.py", line 900, in run_interactive
    self._cli_loop()
  File "/usr/local/lib/python3.10/dist-packages/configshell_fb-1.1.30-py3.10.egg/configshell_fb/shell.py", line 729, in _cli_loop
    self.run_cmdline(cmdline)
  File "/usr/local/lib/python3.10/dist-packages/configshell_fb-1.1.30-py3.10.egg/configshell_fb/shell.py", line 843, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/usr/local/lib/python3.10/dist-packages/configshell_fb-1.1.30-py3.10.egg/configshell_fb/shell.py", line 818, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/usr/local/lib/python3.10/dist-packages/configshell_fb-1.1.30-py3.10.egg/configshell_fb/node.py", line 1406, in execute_command
    return method(*pparams, **kparams)
  File "/usr/local/lib/python3.10/dist-packages/targetcli_fb-2.1.56-py3.10.egg/targetcli/ui_target.py", line 1150, in ui_command_create
AttributeError: type object 'MappedLUN' has no attribute 'MAX_LUN'

**Comment by maurizio-lombardi** [comment]
thanks for the report, there is a reference to a symbol MAX_LUN which has been removed from rtslib, I am going to fix it

**Comment by maurizio-lombardi** [comment]
@tnorman42 Can you please test if this patch fixes the issue for you?

http://bsdbackstore.eu/misc/0001-remove-a-reference-to-MAX_LUN-which-has-been-removed.patch

**Comment by maurizio-lombardi** [comment]
@tnorman42 

https://github.com/open-iscsi/targetcli-fb/pull/201

**Comment by maurizio-lombardi** [comment]
This has been fixed
