### ISSUE TITLE
cannot create pscsi changer using mhvtl changer device

### ISSUE THREAD

**Issue by omac777** [open-iscsi/targetcli-fb#65]
I'm trying to expose an mhvtl virtual media changer device via iscsi.
I'm also trying to associate a real optical drive as one of those devices the media changer can move stuff to.  Any recommendations.  Thank you.

tried /dev/sch0
tried /dev/sg16
tried 8:0:0:0
None of these work.

# targetcli
targetcli shell version 2.1.fb43
Copyright 2011-2013 by Datera, Inc and others.
For help on commands, type 'help'.

/> cd /backstores/pscsi 
/backstores/pscsi> ls
o- pscsi ...................................................................................................... [Storage Objects: 0]
/backstores/pscsi> create name=pscsi_sch0 dev=/dev/sch0
Cannot find SCSI device by path, and dev parameter not in H:C:T:L format: /dev/sch0
/backstores/pscsi> create name=pscsi_sch0 dev=/dev/sg16
Cannot find SCSI device by path, and dev parameter not in H:C:T:L format: /dev/sg16
/backstores/pscsi> create name=pscsi_sch0 dev=8:0:0:0
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/rtslib_fb/tcm.py", line 319, in _configure
    convert_scsi_path_to_hctl(dev)
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/rtslib_fb/utils.py", line 304, in convert_scsi_hctl_to_path
    scsi_device = pyudev.Device.from_name(_CONTEXT, 'scsi', ':'.join(hctl))
TypeError: sequence item 0: expected str instance, int found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/targetcli", line 121, in <module>
    main()
  File "/usr/bin/targetcli", line 111, in main
    shell.run_interactive()
  File "/usr/lib/python3.5/site-packages/configshell_fb/shell.py", line 894, in run_interactive
    self._cli_loop()
  File "/usr/lib/python3.5/site-packages/configshell_fb/shell.py", line 723, in _cli_loop
    self.run_cmdline(cmdline)
  File "/usr/lib/python3.5/site-packages/configshell_fb/shell.py", line 837, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/usr/lib/python3.5/site-packages/configshell_fb/shell.py", line 812, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/usr/lib/python3.5/site-packages/configshell_fb/node.py", line 1406, in execute_command
    return method(*pparams, **kparams)
  File "/usr/lib/python3.5/site-packages/targetcli/ui_backstore.py", line 229, in ui_command_create
    so = PSCSIStorageObject(name, dev)
  File "/usr/lib/python3.5/site-packages/rtslib_fb/tcm.py", line 306, in __init__
    self._configure(dev)
  File "/usr/lib/python3.5/site-packages/rtslib_fb/tcm.py", line 336, in _configure
    lunid)
  File "/usr/lib/python3.5/site-packages/rtslib_fb/utils.py", line 305, in convert_scsi_hctl_to_path
    except DeviceNotFoundError:
NameError: name 'DeviceNotFoundError' is not defined

lsscsi -g
[6:0:0:0]    cd/dvd  MATSHITA BD-MLT UJ260AF   1.00  /dev/sr0   /dev/sg1 
[8:0:0:0]    mediumx STK      L700             0105  /dev/sch0  /dev/sg16
[8:0:1:0]    tape    IBM      ULT3580-TD5      0105  /dev/st0   /dev/sg8 
[8:0:8:0]    mediumx STK      L80              0105  /dev/sch1  /dev/sg17

**Comment by agrover** [comment]
hi, I'm looking into this, trying to reproduce.

BTW tcm_node is part of lio-utils, which should not be needed or used with targetcli-fb versions or recent versions of Datera targetcli.

**Comment by agrover** [comment]
I've verified convert_scsi_path_to_hctl works with scsi_debug devices, I'm not sure why it wouldn't work on a mhvtl device. @markh794 any thoughts?

**Comment by markh794** [comment]
Sorry, I've never actually tried to configure LIO (as yet).
Any chance of a cheat-sheet of LIO commands to get me to this point ?
i.e. Pre-requisits for Linux (My current VM is CentOS 6.7) - so if this can be made to work - that'd great :)
 - list of cmds to setup LIO up to the point of failure.
(If I've needed/wanted iSCSI in the past, I've use TGT and 'pass-through' devices).

I most likely won't be able to look at anything for a couple of days. But more than happy to work with everybody to get it working.
Cheers
Mark

**Comment by markh794** [comment]
OK - I've install the fcoe-target-utils:

[4:0:0:0]    mediumx QUANTUM  Scalar i500      0105  /dev/sch0  /dev/sg11
[4:0:1:0]    tape    IBM      ULT3580-TD4      0105  /dev/st0   /dev/sg7
[4:0:2:0]    tape    IBM      ULT3580-TD4      0105  /dev/st1   /dev/sg8
[4:0:3:0]    tape    IBM      ULT3580-TD4      0105  /dev/st2   /dev/sg9
[4:0:4:0]    tape    IBM      ULT3580-TD4      0105  /dev/st3   /dev/sg10

[root@mhnbu75 ~]# targetcli 
targetcli shell version 2.0rc1.fb16
Copyright 2011 by RisingTide Systems LLC and others.
For help on commands, type 'help'.

/backstores/pscsi> create name=pscsi_sch0 dev=4:0:0:0
SCSI device does not exist.

Hmmm, perhaps an upgrade of targetctl..
Just cloned : https://github.com/open-iscsi/targetcli-fb.git

Now I'm getting an error trying to start targetctl:
ImportError: No module named configshell_fb
Ideas / suggestions ?

Yet:
[root@mhnbu75 ~]# sg_turs -v /dev/sg11
    test unit ready cdb: 00 00 00 00 00 00 

[root@mhnbu75 ~]# sg_inq /dev/sg11
standard INQUIRY:
  PQual=0  Device_type=8  RMB=1  version=0x03  [SPC]
  [AERC=0]  [TrmTsk=0]  NormACA=0  HiSUP=0  Resp_data_format=2
  SCCS=0  ACC=0  TPGS=0  3PC=0  Protect=0  [BQue=0]
  EncServ=0  MultiP=0  [MChngr=0]  [ACKREQQ=0]  Addr16=1
  [RelAdr=0]  WBus16=1  Sync=0  Linked=0  [TranDis=0]  CmdQue=0
    length=36 (0x24)   Peripheral device type: medium changer
 Vendor identification: QUANTUM 
 Product identification: Scalar i500     
 Product revision level: 0105
 Unit serial number: QUANTUM XYZZY_A000

**Comment by agrover** [comment]
Oops, we had an explicit check for type=disk in convert_scsi_path_to_hctl (This is in rtslib-fb, not targetcli-fb btw). I've pushed a fix to open-iscsi/rtslib-fb repo.
