### ISSUE TITLE
Backtrace when attaching tape drive to Backstores/pscsi

### ISSUE THREAD

**Issue by thuynh-brcm** [open-iscsi/targetcli-fb#67]
Attach tape device to /backstores/pscsi using SCSI tape hardware path, system issues backtrace and the tape failed to be attached:

Command:

/> /backstores/pscsi create name=Ultrium-tape dev=9:0:0:0

Backtrace:
Traceback (most recent call last):
  File "/usr/bin/targetcli", line 5, in <module>
    pkg_resources.run_script('targetcli-fb==2.1.fb43', 'targetcli')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_scr  ipt
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1462, in run_sc  ript
    exec_(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 41, in exec_
    exec("""exec code in globs, locs""")
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/targetcli_fb-2.1.fb43-py2.7.egg/EGG-INF  O/scripts/targetcli", line 121, in <module>
 
  File "/usr/lib/python2.7/site-packages/targetcli_fb-2.1.fb43-py2.7.egg/EGG-INF  O/scripts/targetcli", line 111, in main
 
  File "/usr/lib/python2.7/site-packages/configshell_fb/shell.py", line 894, in   run_interactive
    self._cli_loop()
  File "/usr/lib/python2.7/site-packages/configshell_fb/shell.py", line 723, in   _cli_loop
    self.run_cmdline(cmdline)
  File "/usr/lib/python2.7/site-packages/configshell_fb/shell.py", line 837, in   run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/usr/lib/python2.7/site-packages/configshell_fb/shell.py", line 812, in   _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/usr/lib/python2.7/site-packages/configshell_fb/node.py", line 1406, in   execute_command
    return method(*pparams, **kparams)
  File "build/bdist.linux-x86_64/egg/targetcli/ui_backstore.py", line 229, in ui  _command_create
  File "/usr/lib/python2.7/site-packages/rtslib_fb/tcm.py", line 306, in __init_  _
    self._configure(dev)
  File "/usr/lib/python2.7/site-packages/rtslib_fb/tcm.py", line 339, in _config  ure
    lunid)
  File "/usr/lib/python2.7/site-packages/rtslib_fb/utils.py", line 293, in conve  rt_scsi_hctl_to_path
    scsi_device = pyudev.Device.from_name(_CONTEXT, 'scsi', ':'.join(hctl))
TypeError: sequence item 0: expected string, int found

**Comment by agrover** [comment]
It hasn't been in a release yet, but you might try the latest rtslib-fb repo that includes https://github.com/open-iscsi/rtslib-fb/commit/ba87a191edffe01235f86cfb145aa6834f5f0057, which may help this issue.

**Comment by thuynh-brcm** [comment]
Hi Andy,

Thank you very much for your fast response.  I applied your rtslib-fb repo
and still get traceback:


*[root@TargetMode ~]# targetcli*
*targetcli shell version 2.1.fb43*
*Copyright 2011-2013 by Datera, Inc and others.*
*For help on commands, type 'help'.*

*/> ls*
*o- / .....................................................................
[...]*
*  o- backstores ..........................................................
[...]*
*  | o- block .............................................. [Storage
Objects: 0]*
*  | o- fileio ............................................. [Storage
Objects: 0]*
*  | o- pscsi .............................................. [Storage
Objects: 0]*
*  | o- ramdisk ............................................ [Storage
Objects: 0]*
*  o- iscsi ........................................................
[Targets: 0]*
*  o- loopback .....................................................
[Targets: 0]*
*  o- ocs_fc_lio ...................................................
[Targets: 0]*
*  o- qla2xxx ......................................................
[Targets: 0]*
*  o- vhost ........................................................
[Targets: 0]*
*  o- xen_pvscsi ...................................................
[Targets: 0]*
*/> restoreconfig*
*Configuration restored from /etc/target/saveconfig.json*
*/> ls*
*o- / .....................................................................
[...]*
*  o- backstores ..........................................................
[...]*
*  | o- block .............................................. [Storage
Objects: 1]*
*  | | o- hbadisk1 ................... [/dev/sda (111.2GiB) write-thru
activated]*
*  | o- fileio ............................................. [Storage
Objects: 0]*
*  | o- pscsi .............................................. [Storage
Objects: 0]*
*  | o- ramdisk ............................................ [Storage
Objects: 1]*
*  |   o- ramdisk1 ....................................... [(512.0MiB)
activated]*
*  o- iscsi ........................................................
[Targets: 0]*
*  o- loopback .....................................................
[Targets: 0]*
*  o- ocs_fc_lio ...................................................
[Targets: 1]*
*  | o- naa.10000090fa022d78 ......................................
[no-gen-acls]*
*  |   o- acls ........................................................
[ACLs: 2]*
*  |   | o- naa.10000090fa1cc7fe ............................... [Mapped
LUNs: 1]*
*  |   | | o- mapped_lun0 ............................ [lun0 block/hbadisk1
(rw)]*
*  |   | o- naa.10000090fa1cc7ff ............................... [Mapped
LUNs: 1]*
*  |   |   o- mapped_lun1 .......................... [lun1 ramdisk/ramdisk1
(rw)]*
*  |   o- luns ........................................................
[LUNs: 2]*
*  |     o- lun0 .................................... [block/hbadisk1
(/dev/sda)]*
*  |     o- lun1 .............................................
[ramdisk/ramdisk1]*
*  o- qla2xxx ......................................................
[Targets: 0]*
*  o- vhost ........................................................
[Targets: 0]*
*  o- xen_pvscsi ...................................................
[Targets: 0]*
*/> /backstores/pscsi/ create name=Ultrium-tape dev=7:0:0:0*
*Traceback (most recent call last):*
*  File "/usr/bin/targetcli", line 5, in <module>*
*    pkg_resources.run_script('targetcli-fb==2.1.fb43', 'targetcli')*
*  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in
run_script*
*    self.require(requires)[0].run_script(script_name, ns)*
*  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1462, in
run_script*
*    exec_(script_code, namespace, namespace)*
*  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 41, in
exec_*
*    exec("""exec code in globs, locs""")*
*  File "<string>", line 1, in <module>*
*  File
"/usr/lib/python2.7/site-packages/targetcli_fb-2.1.fb43-py2.7.egg/EGG-INFO/scripts/targetcli",
line 121, in <module>*

*  File
"/usr/lib/python2.7/site-packages/targetcli_fb-2.1.fb43-py2.7.egg/EGG-INFO/scripts/targetcli",
line 111, in main*

*  File "/usr/lib/python2.7/site-packages/configshell_fb/shell.py", line
894, in run_interactive*
*    self._cli_loop()*
*  File "/usr/lib/python2.7/site-packages/configshell_fb/shell.py", line
723, in _cli_loop*
*    self.run_cmdline(cmdline)*
*  File "/usr/lib/python2.7/site-packages/configshell_fb/shell.py", line
837, in run_cmdline*
*    self._execute_command(path, command, pparams, kparams)*
*  File "/usr/lib/python2.7/site-packages/configshell_fb/shell.py", line
812, in _execute_command*
*    result = target.execute_command(command, pparams, kparams)*
*  File "/usr/lib/python2.7/site-packages/configshell_fb/node.py", line
1406, in execute_command*
*    return method(*pparams, **kparams)*
*  File "build/bdist.linux-x86_64/egg/targetcli/ui_backstore.py", line 229,
in ui_command_create*
*  File "build/bdist.linux-x86_64/egg/rtslib_fb/tcm.py", line 306, in
__init__*
*  File "build/bdist.linux-x86_64/egg/rtslib_fb/tcm.py", line 339, in
_configure*
*  File "build/bdist.linux-x86_64/egg/rtslib_fb/utils.py", line 293, in
convert_scsi_hctl_to_path*
*TypeError: sequence item 0: expected string, int found*
*[root@TargetMode ~]#*


Regards,
-Thien

**Comment by 36bits** [comment]
This is still an issue when running targetcli-fb v2.1.fb47 and rtslib-fb v2.1.fb64.

Traceback after 'create name=tape dev=4:0:5:0' is:

Traceback (most recent call last):
  File "/usr/local/bin/targetcli", line 5, in <module>
    pkg_resources.run_script('targetcli-fb==2.1.fb47', 'targetcli')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1462, in run_script
    exec_(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 41, in exec_
    exec("""exec code in globs, locs""")
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/targetcli_fb-2.1.fb47-py2.7.egg/EGG-INFO/scripts/targetcli", line 121, in <module>

  File "/usr/local/lib/python2.7/site-packages/targetcli_fb-2.1.fb47-py2.7.egg/EGG-INFO/scripts/targetcli", line 111, in main

  File "/usr/lib/python2.7/site-packages/configshell_fb/shell.py", line 894, in run_interactive
    self._cli_loop()
  File "/usr/lib/python2.7/site-packages/configshell_fb/shell.py", line 723, in _cli_loop
    self.run_cmdline(cmdline)
  File "/usr/lib/python2.7/site-packages/configshell_fb/shell.py", line 837, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/usr/lib/python2.7/site-packages/configshell_fb/shell.py", line 812, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/usr/lib/python2.7/site-packages/configshell_fb/node.py", line 1411, in execute_command
    return method(*pparams, **kparams)
  File "build/bdist.linux-x86_64/egg/targetcli/ui_backstore.py", line 349, in ui_command_create
  File "build/bdist.linux-x86_64/egg/rtslib_fb/tcm.py", line 346, in __init__
  File "build/bdist.linux-x86_64/egg/rtslib_fb/tcm.py", line 395, in _configure
  File "build/bdist.linux-x86_64/egg/rtslib_fb/tcm.py", line 172, in _enable
  File "build/bdist.linux-x86_64/egg/rtslib_fb/utils.py", line 79, in fwrite
IOError: [Errno 22] Invalid argument

And the kernel throws an error: ' pSCSI: udev_path attribute has not been set before ENABLE=1'

After 'create name=tape dev=/dev/st0' the traceback is slightly different:

Traceback (most recent call last):
  File "/usr/local/bin/targetcli", line 5, in <module>
    pkg_resources.run_script('targetcli-fb==2.1.fb47', 'targetcli')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1462, in run_script
    exec_(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 41, in exec_
    exec("""exec code in globs, locs""")
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/targetcli_fb-2.1.fb47-py2.7.egg/EGG-INFO/scripts/targetcli", line 121, in <module>

  File "/usr/local/lib/python2.7/site-packages/targetcli_fb-2.1.fb47-py2.7.egg/EGG-INFO/scripts/targetcli", line 111, in main

  File "/usr/lib/python2.7/site-packages/configshell_fb/shell.py", line 894, in run_interactive
    self._cli_loop()
  File "/usr/lib/python2.7/site-packages/configshell_fb/shell.py", line 723, in _cli_loop
    self.run_cmdline(cmdline)
  File "/usr/lib/python2.7/site-packages/configshell_fb/shell.py", line 837, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/usr/lib/python2.7/site-packages/configshell_fb/shell.py", line 812, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/usr/lib/python2.7/site-packages/configshell_fb/node.py", line 1411, in execute_command
    return method(*pparams, **kparams)
  File "build/bdist.linux-x86_64/egg/targetcli/ui_backstore.py", line 349, in ui_command_create
  File "build/bdist.linux-x86_64/egg/rtslib_fb/tcm.py", line 346, in __init__
  File "build/bdist.linux-x86_64/egg/rtslib_fb/tcm.py", line 383, in _configure
  File "build/bdist.linux-x86_64/egg/rtslib_fb/utils.py", line 121, in is_dev_in_use
OSError: [Errno 123] No medium found


Regards

Jonathan

**Comment by DocCyblade** [comment]
I know this is an old thread, however I was having the same issue. I did the old google thing found a lot of people having this issue. I saw this [Red Hat bug report ](https://bugzilla.redhat.com/show_bug.cgi?id=1672621) and gave me some clues to what is happening. 

Most of us are trying to add the tape drive (usually empty). It's failing on the commands to try and write to the device, because there is no tape. 

For me, loading a tape into the drive, I was able to get it to add the device. I did not mount the tape just put one in.
